<a href="https://colab.research.google.com/github/meshrifalruily/Keras-models/blob/main/Pytorch_multiclass_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from sklearn.datasets import load_iris

In [4]:
X,y = load_iris(return_X_y= True)
X.shape, y.shape

((150, 4), (150,))

# Using Keras

In [6]:
import keras
from keras import layers, models

In [7]:
model = models.Sequential([
    layers.Dense(32, activation='relu'),
    layers.BatchNormalization(),
    layers.Dense(64, activation='relu'),
    layers.BatchNormalization(),
    layers.Dense(3, activation='softmax')

                           ])

loss = keras.losses.SparseCategoricalCrossentropy()
optimizer= keras.optimizers.Adam(learning_rate= 0.001)

model.compile(loss= loss, optimizer=optimizer, metrics= ['acc'])

model.fit(X,y,batch_size=32, epochs=100)




Epoch 1/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 5s 391ms/step - acc: 0.3612 - loss: 1.4525
Epoch 2/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.6593 - loss: 0.7450 
Epoch 3/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.7909 - loss: 0.4864 
Epoch 4/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.8413 - loss: 0.3491 
Epoch 5/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9196 - loss: 0.2732 
Epoch 6/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9689 - loss: 0.2028 
Epoch 7/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9509 - loss: 0.1952 
Epoch 8/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - acc: 0.9559 - loss: 0.1607  
Epoch 9/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - acc: 0.9899 - loss: 0.1135  
Epoch 10/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - acc: 0.9768 - loss: 0.1202 
Epoch 11/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9720 - loss: 0.1236 
Epoch 12/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - acc: 0.9660 - loss: 0.1157 
Epoch 13/100
5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/s

In [9]:
model.evaluate(X,y)

5/5 ━━━━━━━━━━━━━━━━━━━━ 1s 74ms/step - acc: 0.9868 - loss: 0.0286


[0.05461980029940605, 0.9733333587646484]

In [10]:
preds = model.predict(X)
preds.argmax(axis=-1)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# Using Pytorch

In [11]:
import torch
from torch import nn, optim
from torch.utils.data import Dataset, DataLoader
from sklearn.datasets import load_iris

In [26]:
class Dataset(Dataset):
    def __init__(self):
        self.X, self.y = load_iris(return_X_y=True)
        self.X = self.X.astype('float32')

    def __len__(self):
     return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]



In [27]:
data = Dataset()
len(data)

150

In [28]:
data[1]

(array([4.9, 3. , 1.4, 0.2], dtype=float32), 0)

In [29]:
loader  =  DataLoader(data, batch_size=32, shuffle=True)

In [32]:
class Model(nn.Module):
    def __init__(self, input_feature):
        super().__init__()
        self.dense_1 = nn.Linear(in_features = input_feature, out_features=  10)
        self.relu = nn.ReLU()
        self.batchNorm_1 = nn.BatchNorm1d(10)


        self.dense_2 = nn.Linear(in_features =10, out_features= 32)
        self.batchNorm_2 = nn.BatchNorm1d(32)


        self.classifier = nn.Linear(32, 3)
        self.softmax = nn.LogSoftmax(dim=-1)

    def forward(self, input):
        x = self.relu(self.dense_1(input))
        x = self.batchNorm_1(x)

        x = self.relu(self.dense_2(x))
        x = self.batchNorm_2(x)

        x= self.classifier(x)
        output = self.softmax(x)

        return output


model = Model(4)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(params = model.parameters(), lr= 0.001)

epochs = 1000

for epoch in range(epochs):
    for x, y in loader:
        optimizer.zero_grad()
        preds = model(x)
        loss = criterion(preds, y)
        loss.backward()
        optimizer.step()
    if (epoch+1)%20 ==0:
        print(f'epoch:{epoch+1}, loss:{loss.item()}')


epoch:20, loss:0.4171382784843445
epoch:40, loss:0.18035370111465454
epoch:60, loss:0.17935308814048767
epoch:80, loss:0.16691862046718597
epoch:100, loss:0.03381259739398956
epoch:120, loss:0.08565910905599594
epoch:140, loss:0.10697416961193085
epoch:160, loss:0.035712551325559616
epoch:180, loss:0.08742827922105789
epoch:200, loss:0.10638738423585892
epoch:220, loss:0.024195091798901558
epoch:240, loss:0.022818706929683685
epoch:260, loss:0.13060885667800903
epoch:280, loss:0.3710983991622925
epoch:300, loss:0.10677041858434677
epoch:320, loss:0.0940944030880928
epoch:340, loss:0.08932994306087494
epoch:360, loss:0.117387555539608
epoch:380, loss:0.004136584233492613
epoch:400, loss:0.022128669545054436
epoch:420, loss:0.036637865006923676
epoch:440, loss:0.014644217677414417
epoch:460, loss:0.011263217777013779
epoch:480, loss:0.037262532860040665
epoch:500, loss:0.10302379727363586
epoch:520, loss:0.010327107273042202
epoch:540, loss:0.049495186656713486
epoch:560, loss:0.04346005

In [41]:
model.eval()
preds = model(x)


In [42]:
preds.argmax(-1)

tensor([0, 2, 0, 0, 2, 1, 2, 2, 1, 2, 2, 1, 1, 0, 2, 2, 1, 1, 0, 1, 0, 0])

In [43]:
torch.exp(preds)

tensor([[9.9978e-01, 1.9783e-04, 2.4381e-05],
        [3.7349e-05, 2.8214e-03, 9.9714e-01],
        [9.9978e-01, 1.9783e-04, 2.4381e-05],
        [9.9978e-01, 1.9783e-04, 2.4381e-05],
        [1.0091e-07, 1.0740e-07, 1.0000e+00],
        [5.9107e-05, 9.9952e-01, 4.2532e-04],
        [1.4576e-04, 2.7238e-02, 9.7262e-01],
        [1.0917e-07, 1.2354e-07, 1.0000e+00],
        [1.6057e-05, 9.9997e-01, 1.6002e-05],
        [1.0651e-04, 1.6062e-02, 9.8383e-01],
        [1.4091e-06, 1.1695e-05, 9.9999e-01],
        [1.9018e-04, 9.9166e-01, 8.1492e-03],
        [2.6842e-04, 9.7999e-01, 1.9746e-02],
        [9.9978e-01, 1.9783e-04, 2.4381e-05],
        [1.0383e-05, 3.5518e-04, 9.9963e-01],
        [2.8428e-04, 8.5990e-02, 9.1373e-01],
        [2.2042e-04, 9.8790e-01, 1.1882e-02],
        [1.2962e-04, 9.9679e-01, 3.0814e-03],
        [9.9978e-01, 1.9783e-04, 2.4381e-05],
        [9.4399e-05, 9.9852e-01, 1.3837e-03],
        [9.9978e-01, 1.9783e-04, 2.4381e-05],
        [9.9978e-01, 1.9783e-04, 2

In [35]:
torch.exp(preds).argmax(-1)

tensor([0, 2, 0, 0, 2, 1, 2, 2, 1, 2, 2, 1, 1, 0, 2, 2, 1, 1, 0, 1, 0, 0])